# Generated by Django 4.2.7 on 2023-12-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0012_rename_content_comment_text_comment_parent_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="MainApp.post",
            ),
        ),
    ]
